[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GeneralizedAdditiveModels = "cc454e9f-ce0f-441e-b193-468e31ddef4b"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
